# Generated by Django 5.2.7 on 2025-10-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
